Fix treatment of unusual filenames.

diff --git a/wallchanger b/wallchanger
--- a/wallchanger
+++ b/wallchanger
@@ -10,12 +10,15 @@
 ###     does not exist. In fallback mode, wallpapers will not be cycled, but
 ###     only the first one found will be used.
 
-LOGFILE="$HOME/.var/log/wallchanger.log"
-FOLDER="$1"
-TIMEOUT="$2"
-FALLBACK="$3"
+# Signals:
+#
+# SIGUSR1: Next wallpaper
+# SIGUSR2: Set current wallpaper again
 
-set -u
+declare -r LOGFILE="$HOME/.var/log/wallchanger.log"
+declare -r FOLDER="$1"
+declare -r TIMEOUT="$2"
+declare -r FALLBACK="$3"
 
 log() {
     if [[ "$LOGFILE" ]]; then
@@ -29,15 +32,53 @@ output() {
 }
 
 error() {
-    msg="[ERROR] $*"
+    msg="[E] $*"
     echo -e $msg >&2
     log $msg
 }
 
-usage() {
+print_usage() {
     cat << EOF
 usage: $(basename $0) PATH_TO_WALLPAPER_DIRECTORY INTERVAL_IN_SECONDS [FALLBACK_DIRECTORY]
 EOF
+}
+
+detect_screens() {
+    local screencount
+    screencount=$(xrandr | awk '{if ($2 == "connected") {c+=1}} END{print c}')
+    echo $screencount
+}
+
+get_picture_list() {
+    picture_list=()
+    while IFS= read -d $'\0' -r file ; do
+        picture_list+=("$file")
+    done < <(find -H "$1" \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -print0)
+    # -H resolves symbolic links for command line arguments only.
+}
+
+set_wallpaper() {
+    output "[I] Setting wallpaper \"${pic_array[@]}\"."
+    if fehoutput=$(feh --bg-fill --no-fehbg "${pic_array[@]}" 2>&1); then
+        output "[I] Wallpaper set."
+    else
+        error "Setting wallpaper failed:\n\n${fehoutput}\n\n[E] Skipping."
+        return 1
+    fi
+}
+
+next_wallpaper() {
+    pic_array=()
+    for (( i=0; i<$screencount; i++ )) ; do
+        pic_array[$i]="${picture_list[$RANDOM % ${#picture_list[@]}]}"
+    done
+    set_wallpaper
+}
+
+reload_wallpaper() {
+    output "[I] Reloading wallpapers."
+    detect_screens
+    next_wallpaper
 }
 
 fallback_mode=0
@@ -67,14 +108,13 @@ else
     fi
 fi
 
-screencount=$(xrandr | awk '{if ($2 == "connected") {c+=1}} END{print c}')
+screencount="$(detect_screens)"
 output "[I] $screencount screens detected."
 
-output "[I] Looking for pictures in \"$FOLDER\""
-# -H resolves symbolic links for command line arguments only.
-pics="$(find -H $FOLDER \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \))"
+output "[I] Looking for pictures in \"$1\""
+get_picture_list "$FOLDER"
 
-pics_count=$(echo "$pics" | wc -l)
+pics_count="${#picture_list[@]}"
 output "[I] $pics_count pictures found."
 
 if [[ "$pics_count" -eq 0 ]]; then
@@ -89,38 +129,13 @@ elif [[ "$pics_count" -eq "$screencount" ]]; then
     TIMEOUT=0
 fi
 
-set_wallpaper() {
-    pic_array="$@"
-    output "[I] Changing wallpaper to \"${pic_array[@]}\"."
-    if fehoutput=$(feh --bg-fill --no-fehbg "${pic_array[@]}" 2>&1); then
-        output "[I] Wallpaper changed."
-    else
-        error "Setting wallpaper failed:\n\n${fehoutput}\n\n[E] Skipping." 
-        sleep 1 
-        return 1
-    fi
-}
-
-next_wallpaper() {
-    for i in $(seq 0 $(( $screencount - 1 ))); do
-        pic_array[$i]="$(echo "$pics" | shuf -n 1)"
-    done
-    set_wallpaper $pic_array
-}
-
-reload_wallpaper() {
-    output "[I] Reloading wallpapers."
-    set_wallpaper $pic_array
-}
-
 reload=0
 trap ":" SIGUSR1
 trap "reload=1" SIGUSR2
-trap "error \"Unknown error. Terminating.\"" ERR
 
 while : ; do
-    if [[ $reload == 0 ]]; then
-        next_wallpaper || continue
+    if (( $reload == 0 )); then
+        next_wallpaper || { sleep 1 ; continue ; } # retry after 1 second delay
     else
         reload_wallpaper
         reload=0
@@ -135,7 +150,7 @@ while : ; do
     fi
     output "[I] Sleeping for $TIMEOUT seconds."
     sleep $TIMEOUT 2>/dev/null &
-    wait || true
+    wait
     output "[I] Waking up."
 done
 
